# Generated by Django 4.2.4 on 2023-08-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0012_alter_customer_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
