# Generated by Django 4.2.4 on 2023-08-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_orderitem_order'),
        ('store', '0015_alter_cart_id'),
    ]

    operations = [
    ]
